name: Node.js CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    # - name: Lint Code
    #   run: npm run lint

    # - name: Run Tests
    #   run: npm test

    - name: Build and Start Server
      env:
        PORT: 3000
        MONGO_URL: mongodb+srv://arhammustafa:xJY1yqvmyRlyWmkE@ewacommerce.71jye.mongodb.net/ewa_com?retryWrites=true&w=majority&appName=EwaCommerce
        SERVER_URL: 0.0.0.0
        API_URL_ENDPOINT: /api/v1
        ACCESS_TOKEN_SECRET: SDFJKCONHSCGBSDHFGYCNUDSYuisyaciHXNCBCGHTGDJNGBYHBNBXU
        ACCESS_TOKEN_EXPIRY: 10d
        REFRESH_TOKEN_SECRET: JAHXUYENUIYEAUIainxyYEXBITYEAAWBYUbYUteyuetTVYEAgyYJK
        REFRESH_TOKEN_EXPIRY: 30d
      run: |
        npm start
